version: "3.8"

services:
  app:
    build: .
    container_name: bbb-voting-app
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: npm start
    networks:
      - bbb-network

  redis:
    image: redis:latest
    container_name: bbb-voting-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - bbb-network

networks:
  bbb-network:
    driver: bridge
